info:
  component: Configuration Server
spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jotwu123/configuration-repository
        #  basedir: B:\config-service-repo
            
  config:
    name: 
server:
  port: 8888
management:
  context-path: /admin
  
